name: PULL REQUEST

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: send default message
      uses: appleboy/telegram-action@v0.0.8
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        args: |
          [${{ github.repository }}](https://github.com/${{ github.repository }})
          Pull request #[${{ github.event.number }}](${{ github.event.pull_request.html_url }}) ${{ github.event.action }} by [${{ github.event.pull_request.user.login }}](${{ github.event.pull_request.user.html_url }})

          [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
