name: PUSH

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: send default message
      uses: appleboy/telegram-action@v0.0.8
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        args: |
          [${{ github.repository }}](https://github.com/${{ github.repository }})
          ${{ github.event_name }} by [${{ github.event.pusher.name }}](https://github.com/${{ github.event.pusher.name }})
